language: node_js
node_js:
  - "8.10.0"

cache:
  yarn: true
  directories:
    - "node_modules"

env:
  global:
    - CI=true
    - NODE_ENV=production

install:
  - yarn --production=false

script:
  - yarn run ci-verify
